version: '3.5'
services:
  dev:
    user: root
    build:
      dockerfile: spark.Dockerfile
      context: .
    volumes:
      - ./:/spftest/
      - ~/.local/share/virtualenvs:/root/.local/share/virtualenvs:rw
    container_name: spftest_dev
    working_dir: /spftest

  mock-server:
    image: jamesdbloom/mockserver:mockserver-5.13.2
    command: -logLevel INFO -serverPort 1080
    ports:
      - '1080:1080'
    environment:
      - LOG_LEVEL=INFO
      - MOCKSERVER_LIVENESS_HTTP_GET_PATH=/health

  fhir:
    depends_on:
      - mongo
    image: imranq2/node-fhir-server-mongo:2.1.185
    # To use local fhir code, comment above line and uncomment below
#    build:
#      dockerfile: Dockerfile
#      context: ../node-fhir-server-mongo
    environment:
      SERVER_PORT: 3000
      MONGO_HOSTNAME: mongo
      MONGO_PORT: 27017
      RESOURCE_SERVER: http://fhir:3000/
      AUTH_SERVER_URI: http://myauthzserver.com
      CLIENT_ID: client
      CLIENT_SECRET: secret
      INTROSPECTION_URL: https://myauthzserver.com/introspect
      MONGO_DB_NAME: fhir
      CHECK_ACCESS_TAG_ON_SAVE: 1
      IS_PRODUCTION:
      RETURN_BUNDLE: "1"
      VALIDATE_SCHEMA: "1"
      AUTH_ENABLED: "0"
      ENABLE_GRAPHQL: "1"
      LOGLEVEL: "DEBUG"
      SET_INDEX_HINTS: 0
      CREATE_INDEX_ON_COLLECTION_CREATION: 1
      USE_TWO_STEP_SEARCH_OPTIMIZATION: "1"
    ports:
      - '3000:3000'
    command: yarn start
    restart: on-failure
    healthcheck:
        test: ["CMD-SHELL", "curl --silent --fail localhost:3000/health || exit 1"]

  mongo:
      image: mongo:5.0.12
      ports:
          - '27017:27017'
      environment:
          - ALLOW_EMPTY_PASSWORD=yes
      volumes:
          - mongo_data:/data/db
      healthcheck:
          test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet

volumes:
  mongo_data:
