#!/bin/bash

# pre-commit.Dockerfile pulls its base image from the private services-account ECR
# (856965016623.dkr.ecr.us-east-1.amazonaws.com, see CIE-8032). If the docker build
# below fails with "no basic auth credentials" or "pull access denied", run
# `aws sso login --profile services && make ecr-login` and retry.

GIT_PROJECT_ROOT=$(git rev-parse --show-toplevel)
cd "$($GIT_PROJECT_ROOT "$0")"
docker build -f ./pre-commit.Dockerfile -t pre-commit-sam . && docker run --rm --name pre-commit-spf-test-run --user "$(id -u):$(id -g)" -e HOME=/tmp -v $(pwd)/:/sourcecode pre-commit-sam
