version: '2'
services:
  spark:
    image: bitnami/spark:3.2.0-debian-10-r16
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8080:8080'
      - '8081:8081'
      - '7077:7077'
    volumes:
    - ${HOME}:${HOME}
    restart: always
  spark-worker-1:
    image: bitnami/spark:3.2.0-debian-10-r16
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
    - ${HOME}:${HOME}
    restart: always

  mock-server:
    image: jamesdbloom/mockserver:mockserver-5.11.2
    command: -logLevel DEBUG -serverPort 1080
    ports:
      - '1080:1080'
    environment:
      - LOG_LEVEL=DEBUG
      - MOCKSERVER_LIVENESS_HTTP_GET_PATH=/health
